### ISSUE TITLE
GTA V cleaner Not working

### ISSUE THREAD

**Issue by Crzyparot73** [ganeshh123/gta5-cleaner#5] opened 2022-07-10 03:33 UTC
It used to work just fine, and was nice. But I recently deleted all of my mods to try and trouble shoot issues I was having, and I got some new mods, along with reinstalling the cleaner. However, it now only removes some of the mods/scripts instead of all of them.

**Comment by ganeshh123** [comment] 2022-07-18 13:43
Hi could you please try running it from CMD and share a screenshot?

**Comment by Crzyparot73** [comment] 2022-07-18 14:50
I already got it working. It just suddenly started working one day. But I
didn't know how to let you know, my bad.

**Comment by ganeshh123** [comment] 2022-07-18 17:12
This happens with other people too, I suspect it's because the files are being used by some other process and blocked from being moved or deleted. Making sure you quit GTA 5 properly or trying again after restarting your computer would probably fix it.

**Comment by Crzyparot73** [comment] 2022-07-18 17:14
I did, I tried several things, nothing worked. So I stopped for a bit. Then
tried again later and it just somehow worked and has been since

**Comment by ganeshh123** [comment] 2022-07-18 19:10
Weird, a lot of people have the same issue but it can't be pinpointed

**Comment by Crzyparot73** [comment] 2022-07-18 20:37
Yeah, oh well. I hope you're able to find it eventually! Good luck!

**Comment by ganeshh123** [comment] 2022-07-19 11:53
Duplicate of #1

**Closed as completed by ganeshh123** 2022-07-19 11:53 UTC
Labels: duplicate
