### ISSUE TITLE
trojan

### ISSUE THREAD

**Issue by dj3xosphere** [ganeshh123/gta5-cleaner#9] opened 2022-08-06 22:12 UTC
this is a trojan fyi
![dsfdg](https://user-images.githubusercontent.com/110746375/183267565-e2638f8e-ea22-466a-bdbc-de6cdcb32f87.PNG)

**Comment by ganeshh123** [comment] 2022-08-07 11:23
Duplicate of #8

**Closed as completed by ganeshh123** 2022-08-07 11:23 UTC
